Urigo/graphql-scalars

README.md

I didn't know what these are. This may help people in the future. It's a small add that doesn't affect the meaning at all, but may help adoption.

Add a link to scalar types

---

CHANGELOG.md
README.md
package.json
src/NegativeFloat.js
src/NegativeInt.js
src/NonNegativeFloat.js
src/NonNegativeInt.js
src/NonPositiveFloat.js
src/NonPositiveInt.js
src/PositiveFloat.js
src/PositiveInt.js
src/__tests__/NegativeFloat.test.js
src/__tests__/NegativeInt.test.js
src/__tests__/NonNegativeFloat.test.js
src/__tests__/NonNegativeInt.test.js
src/__tests__/NonPositiveFloat.test.js
src/__tests__/NonPositiveInt.test.js
src/__tests__/PositiveFloat.test.js
src/__tests__/PositiveInt.test.js
src/index.js
src/utilities.js

Add a couple of simple scalars that were missed in the first version.

Added NegativeInt and NegativeFloat scalars

---

src/DateTime.js
src/__tests__/DateTime.test.js

Adds support for parsing & serialising numeric dates. It uses the standard JS format of milliseconds since the unix epoch, as this is the native format Date supports.

Support numeric date format

---

README.md

@ardatan please review.
First let's still release a new version under the old name as well to make sure everyone will update (with a deprecation warning like @testing-library has done recently).
Also we need to update the npm badge.

docs(package-name): Updating npm package name to `graphql-scalars`

---

README.md

I know it's so small it's stupid, but it confused me during my spike :)
also: I clicked on the link in the README.md
"Please read our contribution guidelines."
and it leards to
https://github.com/Urigo/graphql-scalars/blob/master/CONTRIBUTING.md
which results in a 404

Update README.md - fix copy-paste mistake

---

src/resolvers/PhoneNumber.ts
tests/PhoneNumber.test.ts

Fix PhoneNumber regex to support more countries

---

.npmignore

There's currently "yarn-error.log" file in the package (npmjs.org).
This will prevent "yarn-error.log" file from being published in the future.

Adding "yarn-error.log" to .npmignore

---

README.md

Exported term is `DateTimeTypeDefinition`, simply to fix comments about using it.

Fix typo 'DateTimeTypeDefinition'

---

README.md
src/index.ts
src/mocks.ts
src/resolvers/UtcOffset.ts
src/resolvers/index.ts
src/typeDefs.ts
tests/UtcOffset.test.ts

**Motivation:**
Date time and Utc Offset seems always together.
Its easier to have 2 scalars for 1 purpose, to input DateTime (example for filtering), and the UtcOffset preferred.

add UtcOffset scalar

---

README.md

Void was added in release 1.1.3 but no reference was added to the docs.

Adding void to the docs

---

src/scalars/Byte.ts
tests/Byte.test.ts

The base64 and hex validators are not guaranteeed to work.
There are some false positive cases, so instead add a type header to
the string, so a user can specify what the encoding of the string is.

fix(Byte): update isHex validator

---

src/scalars/Byte.ts
tests/Byte.test.ts

A leading 0 in the hex string can throw off the hex validator, since
this information is lost in the parseInt action. This results in the
string check to return `false` instead of `true`, because the parsed
hex string does not contain the leading 0.
Related #716
Added a test for a hex string containing a leading 0 (`'04080f10172a'`)
- OS: Mac OS
- GraphQL Scalars Version: 1.7.0
- NodeJS: 14.15

fix(Byte): hexValidator should remove leading 0

---

tests/iso-date/Date.test.ts
tests/iso-date/DateTime.test.ts
tests/iso-date/Time.test.ts
tests/iso-date/__snapshots__/Date.test.ts.snap
tests/iso-date/__snapshots__/DateTime.test.ts.snap
tests/iso-date/__snapshots__/Time.test.ts.snap

Add tests for #826

---

.github/workflows/main.yml
.github/workflows/website.yml
src/scalars/iso-date/validator.ts
tests/iso-date/Date.test.ts
tests/iso-date/DateTime.test.ts
tests/iso-date/Time.test.ts
tests/iso-date/__snapshots__/Date.test.ts.snap
tests/iso-date/__snapshots__/DateTime.test.ts.snap
tests/iso-date/__snapshots__/Time.test.ts.snap
tsconfig.all.json

Support lower case date time strings #469

Support lower case date time strings #469

---

src/scalars/PostalCode.ts
tests/PostalCode.test.ts
website/docs/scalars/postal-code.md

This PR will add the proper regex check for Iran `postalCode` format in scalars.
It should contain only the digits below with the string length of `10`.
```
1, 3, 4, 5, 6, 7, 8, 9
```
Related #991
- OS: `ubuntu 20.04`
- GraphQL Scalars Version: `1.10.0`
- NodeJS: `v14.17.1`

improv(scalars): add Iran postalCode validation

---

src/index.ts

When using the RegularExpression factory in TypeScript the supporting definitions (functions and type) are not exposed. 
Interface: `RegularExpressionOptions`
Type: `RegularExpressionErrorMessageFn`
As a result I had to redefine the types in my code instead of using the `graphql-scalars` one
The change simply exposes these definitions on the root `index.ts` file
https://github.com/Urigo/graphql-scalars/issues/1068
- [X ] Bug fix (non-breaking change which fixes an issue)
Built and unit tested package. Two types were exposed, no functionality otherwise changed
```
yarn build
yarn test
```
- OS: MacOS 10.15.5
- GraphQL Scalars Version: 1.10.1
- NodeJS: 14.17.5

fix: expose RegularExpressionOptions and RegularExpressionErrorMessageFn

---

src/scalars/Byte.ts
tests/Byte.test.ts

Base64 encoded strings contains the following characters: [a-zA-Z0-9+/]. In the current validation of base64 inputs `/` character is missing and it is a valid base64 character.
Updated the base64Validation regex to not fail on valid base64 strings containing `/`.
Related #1088 
- OS:
- NodeJS:
If this is a relatively large or …

Adding support for base64 encoded strings containing / in it.

---

src/scalars/PhoneNumber.ts
tests/PhoneNumber.test.ts

At the moment the phone number regex validates phone numbers with just one digit. Assuming the Niue 7 digits use case is the minimum possible, the regex should be strict on accepting less digits than that.
Related #1190
Created specific unit tests to validate the change.
- OS: Mac OS
- GraphQL Scalars Version: 1.13.1
- NodeJS: 14.18.0

Improve phone number minimum length validation

---

src/scalars/PostalCode.ts
tests/PostalCode.test.ts
website/docs/scalars/postal-code.md

This PR will add the proper regex check for Japan postalCode format in scalars.
ref: https://japan-postcode.810popo.net/
>ZIP codes of Japan are represented by 7 digits numbers using the format 〒NNN-NNNN, where 〒 is the Japanese postal code mark and N is a digit.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test …

feat: add jp postal code

---

src/index.ts
src/mocks.ts
src/scalars/AccountNumber.ts
src/scalars/RoutingNumber.ts
src/scalars/index.ts
src/typeDefs.ts
tests/AccountNumber.test.ts
tests/RoutingNumber.test.ts
website/docs/scalars/account-number.md
website/docs/scalars/routing-number.md

This PR don't require any additional dependency. They are used to validate using checksum, when required, a few banking number types. Account Number spec is Bank dependent and its validity is kept private in US. They can have 5-17 alphanumeric string:
Related #1121 
For ABA Routing Number i …

feat: Add Banking Routing Number

---

src/index.ts
src/mocks.ts
src/scalars/Cuid.ts
src/scalars/index.ts
src/typeDefs.ts
tests/Cuid.test.ts
website/docs/scalars/cuid.mdx

This PR implements a `Cuid` scalar as requested in #756. I also found myself wanting a `Cuid` scalar, so figured i'd try adding one here.
Related #756
Closes #756  
Added unit tests for `Cuid` that test all available apis.
- OS: `linux-gnu`
- GraphQL Scalars Version: `1.17.0`
- NodeJS: `16.15.1`

feat: add Cuid scalar #756

---

website/src/pages/docs/scalars/date.mdx

Date docs seem to imply that input `GraphQLDate` values come through as strings, but they are in fact parsed into `Date` objects, interpreted as UTC. This can be very confusing, when the `Date` representation converts `'2022-09-29'` becomes the `Date` equivalent of `'2022-09-29T00:00:00.000Z'`, which then (depending on time-of-day and your time-zone), can become `Wed Sep 28 2022 17:00:00 GMT-0700 (Pacific Daylight Time)`.
This PR is simply a documentation update, to clarify that these dates are not passed through transparently as strings, but are instead converted to `Date` objects.
Documentation update.

Update docs to clarify that `GraphQLDate` inputs are marshalled as `Date` objects

---

website/src/pages/docs/scalars/date.mdx

Since JS `Date` instances carry a time and timezone component, it's ambigious to what date (without time) they correspond. There's also no concensus between libraries dealing with dates: some use UTC (🥳), others use the local timezone (😡). 
Since it's not necessarily obvious from the outside which approach graphql-scalars use, it's useful to have it explicitely documented. 
-

Clarify date parsing/formatting behaviour for non-utc TZs

---

.changeset/silly-tigers-change.md
src/scalars/PostalCode.ts
tests/PostalCode.test.ts
website/src/pages/docs/scalars/postal-code.mdx

This PR adds a new regex for the Ukrainian postal code in the PostalCode scalar.
Refferance: https://en.wikipedia.org/wiki/Postal_codes_in_Ukraine
> Ukraine uses five-digit numeric postal codes that are written immediately to the right of the city or settlement name.
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

feat: add ua postal code

---

.changeset/curly-pugs-shave.md
src/scalars/DID.ts
tests/DID.test.ts

[did:pkh](https://github.com/w3c-ccg/did-pkh/blob/main/did-pkh-method-draft.md) is a widely used method and should be captured by the regex
(issue #1800)
Added test cases for a did:pkh string

feat: Expand the DID scalar regex to accommodate did:pkh

---

website/src/pages/docs/scalars/dewey-decimal.mdx
website/src/pages/docs/scalars/ipc-patent.mdx

Added markdown files describing the DeweyDecimal and IPCPatent scalars.

Added Markdown file for IPCPatent

---

.changeset/rude-owls-cheer.md
src/scalars/RoutingNumber.ts
tests/AccountNumber.test.ts
tests/RoutingNumber.test.ts

Fixes two minor spelling errors. One that appears in a validation error message of the RoutingNumber scalar. And the other was just a misspelled word in the AccountNumber scalar's tests.
Related # 2224

fix: minor spelling errors

---

.changeset/hip-games-glow.md
src/scalars/json/utils.ts
tests/JSON.test.ts
tests/__snapshots__/JSON.test.ts.snap

This PR handles the literal for `JSONObject` not being an object and throws a proper error.
Related #2285
In my local project I copied the dist/esm dir into my node modules and verified the error is now correct.
It now looks like
```
"JSONObject cannot represent non-object value: \"test\""
```
instead of
```
"Expected value of type \"JSONObject\", found \"test\"; Cannot read properties of undefined (reading 'forEach')"
```
- OS: Mac
- GraphQL Scalars Version: This commit
- NodeJS: Cloudflare Wrangler

fix(JSONObject): Throw proper error if literal is not an object

---

src/scalars/Latitude.ts
src/scalars/Longitude.ts

This will fix the inconsistent types for code-gen for `Latitude` and `Longitude` scalars.
Related [#2168](https://github.com/Urigo/graphql-scalars/issues/2168)
N/A
N/A
- OS: Ubuntu 22.04.3 LTS
- GraphQL Scalars Version: 1.22.4
- NodeJS: v18.16.0

fix(scalars): Latitude and Longitude inconsistent types

---

website/src/pages/docs/scalars/timestamp.mdx

Text is now in sync with the GraphQLTimestamp resolver description in the code.

Fix typo in timestamp.mdx
