Urigo/graphql-scalars

README.md

I think this is the right one.

Update link to contributing

---

src/URL.js
src/__tests__/URL.test.js

[fix] regular expression of URL scalar type

---

package.json
src/BigInt.ts
src/index.ts
src/scalars.ts
types/graphql-bigint.d.ts
yarn.lock

Add BigInt/Long

---

src/resolvers/DateTime.ts

i'm doing something stupid in my code and seeing [Object object]. This would help a lot.

stringify the error message

---

src/resolvers/index.ts
tsconfig.json

Fix typings issue with graphql-type-json

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/urigo/graphql-scalars/117)

fix(docs) Use mocks in mocking section of config.

---

README.md

Proposition to fix #158 
Tell me what you think, happy to change whatever is necessary.

Readme - Add example for apollo-server-express and CommonJS imports

---

src/resolvers/EmailAddress.ts
src/resolvers/GUID.ts
src/resolvers/HSL.ts
src/resolvers/Hexadecimal.ts
tests/GUID.test.ts

Fix GUID Regex

---

README.md

missing VoidResolver import in read me

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature-request.md
.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
README.md

This PR is related to https://github.com/the-guild-org/Stack/pull/9
**NOTE:** You may need to also open up Discussions tab in this repository
- Removed old contributing file since the links are dead (404)
- Added CODE OF CONDUCT and CONTRIBUTING to README
- Added Issue and PR Templates

Contributors update - Code of Conduct, Contributing, README, Templates

---

algolia/config.json

- Fixed the links to be crawled to index the website
- Added the sitemap of GraphQL Scalars website to the list

Fixed config for crawling GraphQL Scalars website,

---

website/docusaurus.config.js
website/package.json
website/src/css/custom.css
website/src/theme/Root.js
website/yarn.lock

The Guild - Components Library integration
https://github.com/the-guild-org/the-guild-components
- [ x ] New feature (non-breaking change which adds functionality)

New header integration

---

website/docusaurus.config.js
website/package.json
website/src/css/custom.css
website/yarn.lock

Algolia Search configuration removal. Component moved to TGC.
https://github.com/the-guild-org/the-guild-components

Algolia Config Removal

---

src/scalars/URL.ts
tests/URL.test.ts

Fix empty string is a valid url
Related #870
- OS: OSX 11.13
- NodeJS: node v12

fix empty string is a valid URL

---

src/scalars/EmailAddress.ts

GraphQLCurrencyConfig → GraphQLEmailAddressConfig

Fix: typo in EmailAddress.ts

---

src/index.ts
src/mocks.ts
src/scalars/DID.ts
src/scalars/index.ts
src/typeDefs.ts
tests/DID.test.ts
website/docs/scalars/did.md

PR for #1168 
Related #1168 
- OS: macOS Big Sur 11.5.2
- GraphQL Scalars Version: v1.12.0
- NodeJS: v16.10.0

feat: add DID scalar

---

website/src/pages/_app.tsx

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
- OS:
- …

fix route to github

---

src/index.ts
src/mocks.ts
src/scalars/Locale.ts
src/scalars/index.ts
src/typeDefs.ts
tests/Locale.test.ts
website/docs/scalars/locale.md

This is a dependency free alternative to #1179 
Related #1177 
Unit tests that verify the language tags conform the [RFC 5646](https://datatracker.ietf.org/doc/html/rfc5646) spec.
- OS: MacOS Big Sur 11.6 (M1)
- GraphQL Scalars Version: 1.14.0
- NodeJS: 16.13.1

feat: Add Locale Scalar

---

website/docs/quick-start.md

Proposal for https://github.com/Urigo/graphql-scalars/issues/1429
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
- OS:
- NodeJS:
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what …

Add config.scalars codegen example

---

.github/workflows/main.yml
package.json

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
- OS:
- …

ci: use shared setup and lint action

---

src/index.ts
src/mocks.ts
src/scalars/SemVer.ts
src/scalars/index.ts
src/typeDefs.ts
tests/SemVer.test.ts
website/src/pages/docs/scalars/sermver.mdx

This PR adds SemVer scalar as discussed in #1701.

feat: add SemVer scalar

---

src/index.ts
src/mocks.ts
src/scalars/IP.ts
src/scalars/IPv4.ts
src/scalars/IPv6.ts
src/scalars/index.ts
src/typeDefs.ts
tests/IP.test.ts
website/src/pages/docs/scalars/ip.mdx

This PR adds the `IP` scalar as discussed in #1714.

feat: add IP scalar
